### ISSUE TITLE
multi tenancy

### ISSUE THREAD

**Issue by AhmedSayed77** [totaljs/flow#10]
is there a way to make it multi tenant? where every tenant has its own flows

**Comment by molda** [comment]
Hi @AhmedSayed77 this is not possible.
Currently the only way is to run one instance of Flow for each tenant.

**Comment by AhmedSayed77** [comment]
Thanks for the quick response. Are there any plans to support that feature in the future?

**Comment by molda** [comment]
No there are no plans for now, but if more people is interested in this then we may try to implemented in the future.

**Comment by petersirka** [comment]
@AhmedSayed77 it's very complicated and multitenancy brings permissions --> and this is a big problem.

**Comment by AhmedSayed77** [comment]
how about accepting a data adapter or a data interface in the options, so that you just call "save" and "get" methods from the adapter/interface, and let me handle the permissions logic?

**Comment by petersirka** [comment]
@AhmedSayed77 we have discussed about it with @molda and as I wrote it's very complicated to implement it and we want to keep simplicity. We know Flow and this is really big thing.
