### ISSUE TITLE
[Security] Stored XSS in platform name

### ISSUE THREAD

**Issue by edoardottt** [totaljs/flow#100]
Tested version: (latest, docker)

Steps to reproduce the vulnerability:
  - Login in the application.
  - Click on settings.
  - Set `"<script>alert(document.domain)</script>` as platform name and save.
  - Logout and XSS will fire.

![Screenshot from 2023-03-25 15-43-27](https://user-images.githubusercontent.com/35783570/227724276-211980ec-7f38-4372-84ad-a34305ba21f4.png)

**Comment by petersirka** [comment]
@edoardottt Thank you. In the Total.js 4 framework, I have fixed the issue https://github.com/totaljs/framework4/commit/e2cea690c3fe4453e94da896a69f832511f65179. There was a missing encoding configuration value for the specific declaration.

You can test it with the Flow: `$ npm install total4@beta`.

**Comment by edoardottt** [comment]
Amazing! You should roll out a patched image too :)

have a nice day!
