### ISSUE TITLE
Cannot install on a read only volume

### ISSUE THREAD

**Issue by developedsoftware** [totaljs/flow#101]
Hi Peter, 

We are attempting to install this on a read only volume which obviously is not going to work because the framework writes to the root of the project. 

Is there a central place we can change or configure to instruct the framework to write and read "runtime" files (such as the pid file, config.json, databases.json to a different volume / folder? 

I looked through the framework and can obviously change manually as needed, but I wondered if I was missing anything obvious....

**Comment by petersirka** [comment]
Hi @developedsoftware,
Disabling this behavior would be a problem. But it's possible with a few modifications. We can help you with our support services or you can change it without us - it's open source.

Of course, I can give you some advice.

**Comment by developedsoftware** [comment]
```
exports.combine = function() {

	var p = F.directory;

	for (var i = 0, length = arguments.length; i < length; i++) {
		var v = arguments[i];
		if (!v)
			continue;
		if (v[0] === '/')
			v = v.substring(1);

		if (v[0] === '~')
			p = v.substring(1);
		else
			p += (p[p.length - 1] !== '/' ? '/' : '') + v;
	}
        
        p = exports.$normalize(p);
        
        if (!Fs.existsSync(p)) {
            return p.replace(F.directory, 'some/writable/path');
        }
        
	return p;
};
```

Currently hacking my way through by changing Utils:combine. Checking if the path exists and if its doesnt we then assume a write is coming and therefore return a writable path. It seems to do that trick (but obviously feels hacky).
