### ISSUE TITLE
Exporting as a Component Performance

### ISSUE THREAD

**Issue by ColtonMcInroy** [totaljs/flow#107]
I experimented more with exporting a flow as a component and I have to say that this is a really nice feature. 

The performance of doing the export though is majorly problematic. I have a flow that is about 100 nodes (two inputs and 1 output) and exporting this flow took forever. The browser hung, asked if the page crashed and I wanted to kill it but I just stepped away and let it go. After about 10 minutes or so, the export screen appeared with the component.

Not sure if it is related to the other performance issue I just posted or not... My thoughts... Depending on the approach taken, if looking for nodes, connections, etc are done via DOM queries, this could be cascading into the performance problem. In my experience it is best to avoid searching the DOM and keep references to elements as much as possible so that any DOM searching is kept to a minimum.

**Comment by petersirka** [comment]
Is it possible to export Flow for us for testing purpose? We need to debug it.

**Comment by ColtonMcInroy** [comment]
Prefer not to have this public yet, so I'll send you the password via private message if you do not mind.
[SchemaBuilder.zip](https://github.com/totaljs/flow/files/12376717/SchemaBuilder.zip)

**Comment by petersirka** [comment]
Great! Thank you

**Comment by petersirka** [comment]
I have improved the Flow designer, but it's not 100% done. It takes half the time for pre-rendering, but there are small issues to solve. I have tested exporting a bigger Flow and confirm that the browser freezes. I suppose that the exported FlowStream is too lengthy for rendering in 'CodeMirror'. I will analyse the problem more deeply this week.

**Comment by petersirka** [comment]
I analyzed this issue again, and we are not able to handle all issues with different cases. I have improved export functionality, but it can still freeze the browser due to the size of the Flow design. I'm closing this issue right now.
