### ISSUE TITLE
Message data values

### ISSUE THREAD

**Issue by ColtonMcInroy** [totaljs/flow#108]
If a message data payload is 0, false, undefined, or null results in message being sent with previous data.

If a component tries to send the above values for any reason, the message gets sent with the contents of the previously received data. Here is a simple example of the behavior.

This example consists of a trigger, code, and print component.
![image](https://github.com/totaljs/flow/assets/121206906/616256f9-eaba-47c2-8546-2e1ed70209bc)

The code component in the middle contains 1 line...
`$.send('output', false);`

Rather than the message being sent with "false" as the payload, the message it sent with the previously set data value. If the code is changed to the following it does appear to work because the data payload has been directly overwritten...
```
$.data = false;
$.send('output', false);
```
And now false is correctly sent to the next component. I am not sure if this is intended behaviour or not, but another user had issues with this on the Telegram support channel so I figured I should report it.

This can be troublesome at times here are a couple examples of problems this issue causes...

The user "Sm*ok" reported an issue trying to do a SQLite3 query resulting in the original $.data being outputted rather than the response of the query.

I myself came across this issue when trying to do a count and if the value was 0 I would end up with old $.data content.

**Comment by petersirka** [comment]
- Fixed: https://github.com/totaljs/framework4/commit/be4fc3a8c6690dbdd297ee47e466e8a749f54fea 
- `$ npm install total4@beta`

---

I'll release it tomorrow.
