### ISSUE TITLE
Run make.sh

### ISSUE THREAD

**Issue by arifsohail** [totaljs/flow#11]
Can we rebuild flow.package after changing the source code. What is the correct way of doing that. I have tried running make.sh file. Gives the following error.
```
./make.sh: line 6: tpm: command not found
mv: cannot stat 'sourcecode.package': No such file or directory 
```
After installing TPM same error persisted.
Then I installed TPM2, Then after running the file I got
```
contextParentFile = flow.package
Argument mismatched!
Please type "tpm2_create -h" get the usage!
mv: cannot stat 'flow.package': No such file or directory
```
Can I use any other TPM command, or is there any other command equivalent of TPM

**Comment by molda** [comment]
How did you install `tpm`? I mean the tpm command is available after installing framework globally `npm i total.js -g`, have you done this?

**Comment by molda** [comment]
Also if you rename the `source` folder to flow.package and copy that folder to ./packages it will work.

**Comment by arifsohail** [comment]
I was getting command not found so, I installed it. Thanks for the Help, It really worked after I changed the name of source to flow.package :) :+1:  @molda

**Comment by ductran54** [comment]
Hello, do you have a component to execute a command in flow (such as make.sh) and send to its response to a next flow component if received from .sh?

**Comment by petersirka** [comment]
@ductran54 currently we don't have any similiar component, but I'll create it today/tomorrow, OK?

**Comment by ductran54** [comment]
Yes, thank you!

**Comment by ductran54** [comment]
Hi Peter, did you create the Command Execution component in Flow yet?

**Comment by petersirka** [comment]
Hi, sorry for big delay... I have it in my another Mac and tomorrow I'll publish it.
