### ISSUE TITLE
New to total.js flow I don't know to use add link endpoint

### ISSUE THREAD

**Issue by virtuehive** [totaljs/flow#114]
hello I'm new to totaljs flow and there is add link endpoint facilities . I try this , get JSON result from http GET and it create new component. It can't show to print or print component so I can't use it as input to other components. need help

**Comment by petersirka** [comment]
Yes, `Add link` creates a new component that downloads data from the endpoint and sends it next. So if you connect the output from the "link" component with a print component, you must see the result.

**Comment by virtuehive** [comment]
I don't see anything in print component and debug

**Comment by virtuehive** [comment]
do it need trigger component? video tutorial in integrating many REST API should be very helpful

**Comment by petersirka** [comment]
> do it need trigger component? video tutorial in integrating many REST API should be very helpful

Of course, Link component needs input data.

**Comment by petersirka** [comment]
Please make a thread for discussion because this is not an issue.
