### ISSUE TITLE
Self hide component

### ISSUE THREAD

**Issue by joaomirandasa** [totaljs/flow#12]
Hi everyone, 

I was creating an application on TotalJS + Flow installed but now I have a lot of components installed at my tabs and when I click to add some component or duplicate one tab this action just not completed and I didn't receive any error message. component or tab just self hide and I don't no what to do. Someone get this error? or know what to do?

**Comment by molda** [comment]
Hi @joaomirandasa try to increase request length limit by adding bellow line to your config file:

    module#flow	(Object)		: { limit: 1024 } 

default limit is 50kB

**Comment by joaomirandasa** [comment]
I tried this right now and nothing changes, when I add a new component or tab this just gone away. I feel this can be something related to allocated memory or similar, I check my servers capacity and not full wet, I have a lot of free memory space to process. 

If @molda have any ideia we can make a voice call, Skype/WhatsApp/Zoom to discuss. Please help me fix this to back to work.

Thank You.

**Comment by molda** [comment]
Is there any chance you could send me your app as it is now so i can check what's going on?

**Comment by petersirka** [comment]
@joaomirandasa we need to see server logs from Total.js app. Then open `Traffic` tab and send me memory consumption. And as wrote Martin, we need to see app and debug it.

**Comment by joaomirandasa** [comment]
hello again friends, 

Today I wakeup and have a different ideia of @molda told me, when I checked my configure file i saw previously changes on Flow edited on 

@molda  --> `module#flow`   My changes --> `package#flow	(Object)		: { limit: 1024 } `

So I change what @molda say and appears going good.    
I yet have questions about program, i dont discover on documentation or related posts about self close connection using socketIO + TotalJS + Flow, you see this at some moment before?! socket io just close connection and restart my chatbox.

Thank you a lot @petersirka and @molda about support and explanations, Flow is an awesome tool and I would like be a collaborator at Brasil, maybe I can translate this for community or create components to share.

**Comment by petersirka** [comment]
@joaomirandasa sorry for delay. Total.js Flow doesn't user Socket.io. Do you use a reverse proxy?

**Comment by joaomirandasa** [comment]
Hello again, 

@petersirka Yess! i'm using reverse proxy on Ubuntu 14.04, my operations going well.
Let me explain a little bit better, I create an chat using Flow + TotalJS and embed Socket.io to create clients connection, but sometimes socket or totals (I didn't discover), close and reopen socket connection, I tried edit my configures on reverse proxy but nothing changes. Any idea?

`
# Default server configuration
#

server {
		listen 80 default_server;
		listen [::]:80 default_server;

		root /var/www/html;

		# Add index.php to the list if you are using PHP
		index index.html index.htm index.nginx-debian.html;

		server_name _;

		location / {
	        proxy_set_header   Host             $http_host;
            proxy_set_header   X-Forwarded-Protocol $scheme;
            proxy_set_header   X-Forwarded-For  $remote_addr;
            proxy_set_header   X-NginX-Proxy    true;
            proxy_pass         http://0.0.0.0:8000;

            # max 15 minutes keep-alive
            proxy_read_timeout  600s;

            proxy_redirect     off;
            proxy_http_version 1.1;
            proxy_set_header Upgrade          $http_upgrade;
            proxy_set_header Connection       "upgrade";
            break;
		}

	}

server {
		listen 443 ssl default_server;
		listen [::]:443 ssl default_server;
		server_name ****.MY.WEBSITE;

		

	    access_log            /var/log/nginx/*****.access.log;

		root /var/www/html;

		# Add index.php to the list if you are using PHP
		index index.html index.htm index.nginx-debian.html;

		location / {
			proxy_pass http://localhost:8000;
			proxy_redirect      http://localhost:8080 https://****.MY.WEBSITE;
			proxy_http_version 1.1;
	        proxy_set_header Upgrade $http_upgrade;
	        proxy_set_header Connection 'upgrade';
	        proxy_set_header Host $host;
	        proxy_cache_bypass $http_upgrade;
	        proxy_read_timeout  600s;
		}

}`

**Comment by petersirka** [comment]
So you're providing `Socket.io` with `Total.js` together, right? If __yes__ then it's not good. Total.js Flow can't use `Socket.io` and `Socket.io` can't use `Total.js` websocket --> so the bug can be here. Nginx config looks good.
