### ISSUE TITLE
about installation

### ISSUE THREAD

**Issue by Arya0616** [totaljs/flow#16]
I am not sure what ''download and copy flow.package into the /packages/ directory or create a definition file with'' exactly means,  do I need to create a new file?

**Comment by Arya0616** [comment]
well I got it, after I download emptyproject-flow and run it, . I clicked on the Database icon ,but there is no pred-defined templates. how can I solve it?
![utcq7qmpyidefl5 mobe69s](https://user-images.githubusercontent.com/28853484/38665509-26d5f706-3e6f-11e8-9c81-523e907a611a.png)

**Comment by petersirka** [comment]
Are you sure you have internet connection? Because templates are downloaded from GitHub. Try to look into the console whether it contains some error or no.

**Comment by Arya0616** [comment]
yes I'm sure I  have internet connection, but it seems the console doesn't contain error
![k22xzmrt fv7e24n 9 6t](https://user-images.githubusercontent.com/28853484/38665824-f66f8a7c-3e6f-11e8-8057-13d82f3c757e.png)

**Comment by petersirka** [comment]
I meant `console` as a terminal output.

**Comment by Arya0616** [comment]
you mean this?
![o01 ep22 r f1pcgqvei0d](https://user-images.githubusercontent.com/28853484/38665938-47bbb770-3e70-11e8-9527-0f613da25d1b.png)

**Comment by petersirka** [comment]
Please write me on Total.js Messenger __petersirka__: https://messenger.totaljs.com

**Comment by Arya0616** [comment]
ok thanks
