### ISSUE TITLE
[questions] about flow

### ISSUE THREAD

**Issue by trsh** [totaljs/flow#17]
First of all this is brilliant. 
But I do have some doubts and questions:

1) How/where is the node info stored?

2) What the performance hit? I mean the logic needs to parse (compile?) the nodes, before executing something? Or are the nodes run as pure JS? I could not understand from code.

3) Can I create new node (sure I can?), and run in there some very custom and advanced logic?

4) Is some kind of versioning and/or draft-publish feature planed for the schema? Because you can just mess around with an API, for example :)

5) Is a Module feature planed, where I can make a node group and reuse, just like in OOP?

**Comment by petersirka** [comment]
Hi @trsh,
sorry for delay.

__How/where is the node info stored?__
Flow schema is stored in json-plain-text file `/your-app/flow/designer.json`

__What the performance hit?__
Nodes are compiled to raw JS (and Node compiles it to native code), so components/nodes are very fast.

__Can I create new node?__
Of course. Here are all open-source components: <https://github.com/totaljs/flowcomponents> and you can create some according to your needs. Just duplicate and modify.

__Is some kind of versioning and/or draft-publish feature planed for the schema?__
Our idea is nothing to change in Flow. So we want to keep current funcionallity.

__Is a Module feature planed, where I can make a node group and reuse, just like in OOP?__
I don't understand.  You can reuse your own components and you can export Flow schema and import into the another Flow.

**Comment by trsh** [comment]
@petersirka 

> Our idea is nothing to change in Flow. So we want to keep current funcionallity.

The problem is that sometimes, you do not wan't the schema logic to be replicated right away because you are still messing around (just like writing an article for blog - first is draft and then u publish). And sometimes you want to roll it back to prev state - just like we do with standard code via Git, something seems to be needed also for this visual programming via nodes. What's your opinion?

> I don't understand. You can reuse your own components and you can export Flow schema and import into the another Flow.

Let's say you have a node logic: Component A -> Component B -> Component C -> Component X and you need this "Component A > Component B > Component C > Component X" in multiple places. Its a bit of time and space consuming to repeat it all. But if it could be grouped and reused..

https://code.blender.org/wp-content/uploads/2012/01/node_group_interface8.png

What's your opinion?

**Comment by petersirka** [comment]
@trsh 

Flow supports backups of Flow schemas, but there is a small lack - you need to recover schema manually according to the date. This mechanism will be updated in the near future. In other words: if you change the Flow schema then Flow will create an independent backup file with older Flow schema.

__Groups__:
Now I understand. This is not possible yet, but as idea why not ... Flow supports Tabs, now you can group some components in different tabs. @molda created these components some time ago: https://www.youtube.com/watch?v=njhmir5lJ1A and with these components you can communicate between some components in different tabs.

I'm open for all good ideas.

**Comment by trsh** [comment]
@petersirka ok, clear. And thanks for the reply in a weekend.

**Comment by petersirka** [comment]
No problem, thank you too.
