### ISSUE TITLE
Loop inside Flow Element

### ISSUE THREAD

**Issue by joaomirandas** [totaljs/flow#19]
Hello, 

I work a lot with flow designer and components but now i had one trouble where i cant imagine what to do, imagene that way: I sending some information to on flowcomponent ( one block ) on my screen, i processed this info but now i need recreate data just like seen received from last block, one way to do a loop with information, resend this to INSTANCE.on('data', 

Important: without use external connections or IO elements on screen, an internal way to do a loop.

some one already do something like that?

**Comment by petersirka** [comment]
Hi @joaomirandas, you can use `code` component for this and if you have your own component you can resend data very easy:

```javascript
instance.on('data', function(message) {

    // but be careful for infinite loop:
    instance.emit('data', message);


});
```

**Comment by petersirka** [comment]
I will think about it and then I will contact you.
