### ISSUE TITLE
[Flow] Does not work after component Refresh

### ISSUE THREAD

**Issue by KangGS** [totaljs/flow#24]
Does not work after component Refresh.
After you update a component, it will not work until you create a new component or restart the program.

help me ..

**Comment by petersirka** [comment]
Hi, you need to upload component again, or restart app or just enable <https://wiki.totaljs.com/flow/02-configuration/#property-debug->

**Comment by KangGS** [comment]
my "config" file ->
package#flow       (Object)  : { url: '/flow',  debug:true}

same...
Did I misuse the "debug"?

**Comment by vasekd** [comment]
It seems that the component is reloaded, but not registered properly.
Use case:
1. Add debug component to the flow  => You will see the status Enabled in the workspace
2. Reload the component on the disk => the yellow notification is shown. Same as on the video
3. The status message 'Enabled' disappear and the component is not working.

**Comment by petersirka** [comment]
@vasekd  there was a bug 👎. I have fixed it 👍... Just download `flow.package`.

**Comment by vasekd** [comment]
Thanks you very much. It works very well.

**Comment by KangGS** [comment]
Thanks you very much!
