### ISSUE TITLE
Is it possible to create a Flow visually, then run it stand-alone somewhere else with no GUI?

### ISSUE THREAD

**Issue by robhawkes** [totaljs/flow#27]
First off, I want to say how cool Flow looks — I've been searching for a decent visual programming system for a while and I think Flow fits the bill. However, I have a question about how it can be used.

For my use-case I'd like to use the visual designer for constructing and testing the initial flow, however I'd want to run the flows manually as and when I want. Is it possible to save a flow from the designer and then run it separately to the GUI?

Specifically, I'd be talking about creating flows locally using the designer, saving them in sane way (eg. JSON/a package), and then running those flows in a headless way on a remote server (which I don't want to have the GUI, nor any ability to create or modify flows).

Is this possible?

**Comment by molda** [comment]
Hi Rob,
yes it is possible.
You can run the Flow in 3 modes.
- both client and server
- only server, this is probably what you want
- only client, usefull to connect to "only server" instance

See the options `options.type` and `options.external` [here](https://github.com/totaljs/flow#installation)

**Comment by sb-saurabhbhosale** [comment]
Hey, @robhawkes have you implemented the above scenario?
If you have done anything could you please share some snippets of code?

**Comment by petersirka** [comment]
@sb-saurabhbhosale:

- both: this repository
- server only: https://github.com/totaljs/flowstreamworker
- client only: https://github.com/totaljs/flowstreamdesigner (but not same designer)
