### ISSUE TITLE
[component] exports.icon cannot contain dash

### ISSUE THREAD

**Issue by lgrkvst** [totaljs/flow#31]
I can for instance define a flow/component.js with:
`exports.icon = "pen";`

However not with:
`exports.icon = "pen-square";`

Can anyone reproduce this?

**Comment by petersirka** [comment]
You need to choose an icon according to this list:
https://fontawesome.com/icons?d=gallery&m=free

**Comment by lgrkvst** [comment]
Oh. Right.

Thanks =)

**Comment by yusef-ho** [comment]
@petersirka  Hello,
i put "fab fa-line" according to description and https://fontawesome.com/v5.15/icons/line?style=brands
but now working
