### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by joaomirandasa** [totaljs/flow#32]
Hi guys, i faced an error inside Flow, i have about 15 tabs and a lot of components ( about 2000 )  running for my instances, but sometimes i stay out of FlowTab ( at browser ) when i back my aplication breaks, i connect Sentry ( error tracking ) weeks ago to get more information about it, now can i have a lot of content to share. But not cetain how to handle with this. If possible i will be really glad to have some ideias.

My error is:

```
TypeError: Converting circular structure to JSON
  File "/var/www/SERVER/tmp/flow.package/index.js", line 1774, in Timeout.FLOW.save2 [as _onTimeout]
    var json = JSON.stringify(data, (k,v) => k === '$component' || k === 'comreadme' ? undefined : v, '\t');
...
```
I already think in handle this using adn try-catch script but i realize i cna lose my entirely flow data doing this wrong. Any idea here??

SPECIFIC Line of error:

`var json = JSON.stringify(data, (k,v) => k === '$component' || k === 'comreadme' ? undefined : v, '\t');`

**Comment by petersirka** [comment]
Hi @joaomirandasa,

first, can you send a screenshot of your Flow? I can't imaging around 2000 components and 15 tabs :-D. How many CPU and memory does it take? I'm curious.

__The problem:__ do you have some custom components? There can be a problem in `options` of some component because the component can contain a reference to itself.

I have prepared a small script which can help you to find a problem:
<https://www.dropbox.com/s/7ibkgcktxpcz0u0/test.js?dl=0>

- copy this script to `/your-flow-app/definitions/`
- restart app
- script will perform test after 10 seconds
- watch the terminal output / console
- then send me the bad component

Really I'm courious.

**Comment by joaomirandasa** [comment]
Hi again Peter, 

First of all, thankyou thank you thanyou to provide this awesome software to us! I really love TotalJS in special Flow! I take a look at solution of you provide and sounds like perfect! i could'nt think anythink better than that.

For you curiosity, i design a lot of components to Flow, most of them have more the 9 variables and 600 lines ( each ). I use in my project and it's not related to serves but specif for communication within my business. I made modifications in flow(index.js) to make my life easy, just like flow.reload() launched now - i design this solution 7 month ago, because most part of time i need to update components variables externally, i also translate entirely flow to "pt-BR".

When i discover more about related error i will post here, please don't close this thread yet - if i fix by myself i let us know, but if not i will back here to keep discussion. THANK YOU AGAIN.

look one of my flows: https://www.dropbox.com/s/6tksnmyjylk7z8d/Captura%20de%20Tela%202019-05-04%20%C3%A0s%2010.15.23.png?dl=0

**Comment by joaomirandasa** [comment]
Yeah, thanks to your proposal i discovered where is my error, inside on block designed by myself - now i will fix this and what we learn with this is we could create some functions to avoid breakouts or something like that, an module of security or error tracking inside TotalJS library, i will keep thinking about it, if i design something be shared
Thankyou again.

**Comment by petersirka** [comment]
I'm closing this issue. If you will have a problem - just write me.
