### ISSUE TITLE
Limit the number of inputs for a component?

### ISSUE THREAD

**Issue by DPain** [totaljs/flow#40]
Hi, is there a way to currently limit the number of inputs of a component?

In the javascript file of the component, there is a setting 'input' that allows numbers and lists, but that only modifies the number of circles that appear on the component box.

Even if I set input = 1, I can still link more than one component into the input of the component.

I checked both the docs for totaljs/flow and totaljs/flowcomponents and I couldn't see anything related.

**Comment by petersirka** [comment]
__This is not possible.__ You can't limit a count of components on inputs/outputs. Maybe we can update Flow library by adding a new option for limiting count of components, but I don't imagine for what.
