### ISSUE TITLE
How to pragmatically know if an input for a component is connected ?

### ISSUE THREAD

**Issue by piyusharorawork** [totaljs/flow#41]
From the documentation , I found out that every instance has connections object to tell how many output connections per instance of the component are connected . 

Is there any way where I can find out whether input connection of the  instance of the component  is connected to any other instance 

e.g.  
![Selection_001](https://user-images.githubusercontent.com/31386968/60679931-07da8800-9ea7-11e9-845c-e32a2a96bb5b.png)

In the above image , i will get 2 connections but no info in the input connections . 

Please let me know if you got something to fix this .

**Comment by molda** [comment]
https://github.com/totaljs/flow/blob/master/readme.md#component

See `component.inputs();`

**Comment by piyusharorawork** [comment]
@molda 
Thank you , I dont know how I missed that :D.
