### ISSUE TITLE
Client vs Server vs Bundle?

### ISSUE THREAD

**Issue by jvillacis** [totaljs/flow#45]
I noticed there are 3 modes that totaljs flow can be ran on (client, server, bundle) and I was wondering what the differences between the 3 modes are. Thanks!

**Comment by petersirka** [comment]
Hi @jvillacis,
yes.

- __client mode__ will run `Flow designer` only without Flow backend. This mode needs to define `options.external` which will contains external address for WebSocket connection between designer and Flow backend
- __server mode__ will run `Flow backend` only without Flow designer, so in this version you can't use UI Flow designer
- __bundle__ is standard version with Flow designer + Flow backend

We have prepared Flow for multiple usage and we want to publish one more tool for controlling of multiple Flows :-)
