### ISSUE TITLE
Running flow from source, not package?

### ISSUE THREAD

**Issue by benbenbenbenbenben** [totaljs/flow#46]
How can I run flow without using the package? We're working on some accessibility changes and we don't want to have to repackage flow every code change and test.

What is the correct way to run flow without using the package system?

**Comment by petersirka** [comment]
Hi,
- just create a directory called `/yourapp/packages/flow.package/`
- copy all files from flow `/source/` directory
- run app and you can modify files in the directory directly without rebuilding Flow

**Comment by petersirka** [comment]
BTW: if you want to take Flow designer to another project then I recommend to use our client-side component called `j-Flow`: https://componentator.com/components/j-flow/
