### ISSUE TITLE
Running make.sh gives me an error.

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/flow#48]
|==================================================|
| Total.js - Web framework for Node.js             |
| Version: v3.2.4                                  |
|==================================================|

ERROR: directory does not exist

mv: 'flowpackages.package'...

If you modify 'totaljs --package "$NAME"' to 'tpm create "$NAME"', you will not get an error.

Is it because my version is low?

**Comment by petersirka** [comment]
Hi, sorry we have prepared configuration for new version of Total.js framework. Try to install latest stable beta version: `$ npm install -g total.js@beta` as a global module, I belive that it will work.

**Comment by KangGeunSu** [comment]
Thank you~
Good luck!!
