### ISSUE TITLE
Multiple FLOWs on a server

### ISSUE THREAD

**Issue by quoctri1** [totaljs/flow#50]
Hi @molda and @petersirka, is there any way to create multiple FLOWs on a server?

**Comment by molda** [comment]
Do you mean if you can run multiple Flow apps on a single server?

**Comment by molda** [comment]
Then yes you can run as many Flow apps as your server can handle.
Flow is a node.js application so if you can run multiple node.js apps on your server then multiple Flows should be no problem.
You need to run them on different ports of course.

**Comment by quoctri1** [comment]
Thank you so much
