### ISSUE TITLE
flow.type client mode error!

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/flow#53]
Hello
Testing the mode in the flow.package
flow version : 6.14
total.js version : 3.3.0
server flow : localhost:8000
client flow : localhost:8001
In client mode, typing "ws://localhost:8000" in external will not be recognized because of the port.

I want to do an internal test without a domain, what should I do?

"ws://localhost:8000" or "ws://localhost\:8000" or "ws://localhost%3A8000"
All fail.

Thankyou.

**Comment by petersirka** [comment]
Hi,
fixed.

**Comment by KangGeunSu** [comment]
Thank You~! :)
