### ISSUE TITLE
How to access total cloud with US phone?

### ISSUE THREAD

**Issue by logicbomb** [totaljs/flow#55]
Is there a way to create an account for the cloud without SMS?  been waiting 20 minutes for the confirmation code.  US phone number I've tried a few formats - +1xxxxxxxxxx & 001xxxxxxxxxx

**Comment by petersirka** [comment]
Hi, where? On platform.totaljs.com?

**Comment by logicbomb** [comment]
yes

**Comment by petersirka** [comment]
Please send me:
- firstname + lastname
- email
- phone number
- company
- position (developer/manager)
- country
- gender

to my email address petersirka@gmail.com, I'll create account for you - ASAP.

**Comment by logicbomb** [comment]
thanks, I'm in
