### ISSUE TITLE
Integrate our Custom HTML and CSS with flow 

### ISSUE THREAD

**Issue by Prince-1501** [totaljs/flow#56]
Hello Everyone,
Is there are any methods from which I can integrate My custom Login and Signup Page with the flow totaljs.
I have created a flow diagram or more specifically, I created a Route or endpoints like /POST or /GET to store person credentials. But unable to integrate with my custom forms.

This is the flow i created and I have a form page also.

![Screenshot 2020-05-16 at 12 20 10 PM](https://user-images.githubusercontent.com/37762770/82112950-a2665180-976f-11ea-9e59-f436d2229cb6.png)

Please guide me 
Thank you

**Comment by petersirka** [comment]
Hi,
do you want to provide custom pages in this app where is running flow or somewhere else? Why is problem to integrate your forms?

I don't know whether is good idea to write own REST endpoint directly in Flow. I tried it a long time ago and yes - the app and control is really nice, but error handling and advanced features must be written manually in `Code` component or directly in code.

**Comment by Prince-1501** [comment]
Thank you @petersirka 
Then, I think I have to write the REST endpoint from basics in Nodejs?

**Comment by petersirka** [comment]
It's my personal recommendation. BTW: you can write REST endpoints in Total.js directly - it's very easy and e.g. you can use own Cloud services (you can test it for free for 24 hours) and there is this REST template: https://github.com/totaljs/emptyproject-restservice

In our cloud you can code directly in web browser, we use our cloud based editor too.

**Comment by digitalibi** [comment]
Hey Peter, we have been exploring Totaljs for an insurance platform that we want to build. 
Need guidance and confidence that we can use total js and its flow based editor to make the app.
Flow editor is nice but not sure how the code output can have API to integrate with react or any other front end framework.

**Comment by petersirka** [comment]
Hi @digitalibi,

> Need guidance and confidence that we can use total js and its flow based editor to make the whole backend.

We have a lot of projects (from IoT to intranet apps), so you can trust Total.js and Total.js Flow too. Our company is providing more than 100 apps written in pure Total.js. Everything you see to www.totaljs.com is written in Total.js, Total.js doesn't have similar competition - really.

> Flow editor is nice but not sure how the code output can have API to integrate with react or any other front end framework.

Flow can communicate with everything. You can create REST endpoints or you can send/receive data via WebSocket, TCP or UDP. There is thousands of ways how to integrate Flow with everything. Our platform offers a great UI library and you can use more than 200 UI components absolutelly for free: https://componentator.com and there is j-Flow component too, so you can create own implementation of Flow - e.g. multi tenant Flow or Flow for some business processes/workflows, etc..

**Comment by digitalibi** [comment]
HI Peter, Thanks for your reply.
Can I get few minutes on call with you as you are the founder of total js. Need some guidance. 
Thanks in advance

**Comment by petersirka** [comment]
You can write us via our Messenger, https://platform.totaljs.com
