### ISSUE TITLE
notes Bug

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/flow#58]
hello.
I found a bug in "info-panel"

httprouter has a note, but I can't see it

index.html
notes && el.find('.markdown').html(markdown(notes, el));
>>
notes && el.find('.mt5').html(markdown(notes, el));

I think it should be modified like this

I'm sorry I didn't speak English well....Thank you

**Comment by petersirka** [comment]
Hi,
I have tested it and everything works correctly:

![image](https://user-images.githubusercontent.com/2414252/88626062-4773a380-d0aa-11ea-96f1-5f09ba460d65.png)

Can you create an example project with Flow and with that component? I need to simulate it.

Thank you!

**Comment by KangGeunSu** [comment]
What I said is not "readme", but "notes".

If you save "router", it should look like this.

![스크린샷, 2020-07-28 16-59-18](https://user-images.githubusercontent.com/11586458/88636658-2e8fe000-d0f4-11ea-92d1-2a67e14d7630.png)

Thank You!

**Comment by petersirka** [comment]
Shit, sorry - my bad. I'll check it.

**Comment by KangGeunSu** [comment]
Thank you!

Hope you always have a good day!

**Comment by petersirka** [comment]
Fixed, thank you!
Just download `Flow` package.
