### ISSUE TITLE
http route bug..

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/flow#60]
Hello, 
Congratulations on the Total4 launch.

but.. Http route is not working

UNINSTALL is not defined ReferenceError: UNINSTALL is not defined
at Component.instance.reconfigure (/home/kgs/KGS/git/emptyproject-flow/flow/httproute.js:192:3)

**Comment by petersirka** [comment]
Hi @KangGeunSu,
Thank you. Temporary: I recommend to use Total.js v3 for Flow due to 100% backward compatibility. Not all components are compatible with Total.js 4 yet.

**Comment by KangGeunSu** [comment]
OK! Thank you
See you next time!
