### ISSUE TITLE
Localization of Components 

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/flow#62]
The menus of "FLOW" have been localized.

However, it did not become a component.

Should I give you another option?

Note, 
it is applied as default.resource. 
FLOW is Other.resource.

Thank You~

**Comment by KangGeunSu** [comment]
Additionally found "self.language" in "FN.websocket".

But I didn't find the part that sets "self.language" anywhere.

**Comment by petersirka** [comment]
Hi @KangGeunSu, do you mean localization for the components?

**Comment by KangGeunSu** [comment]
Yes, I do

**Comment by petersirka** [comment]
Try to update `flow.package` (https://github.com/totaljs/flow) - I think that I have fixed localization.

**Comment by KangGeunSu** [comment]
sorry, client.req.$language is seems to be the PC setting..

I would like it to be set to "LOCALIZE".

**Comment by petersirka** [comment]
Hi @KangGeunSu, yes - `language` can be set in `LOCALIZE()`.

**Comment by KangGeunSu** [comment]
LOCALIZE(function(req, res) {
    // if "query.language" will be undefined then the framework uses default resource
    return req.query.language;
});

If you add the code above, then "Flow UI" is applied, but the inside of "Component" is still default.

http://localhost:8001/?language=ko
Info, console... is to 정보, 콘솔
![image](https://user-images.githubusercontent.com/11586458/110446974-19a41200-8103-11eb-8cf6-3163f0c104e9.png)

but, The inside of "Debug" remains the same.
![image](https://user-images.githubusercontent.com/11586458/110447298-6e478d00-8103-11eb-98cf-ddfe3a220cfe.png)

Also, client.language is undefined.

**Comment by KangGeunSu** [comment]
my ko.resource

`
// debug.js
Tcyyznd      : 출력 타입
Tl8ltdw      : 예: 온도
T1h73owc     : 그룹 이름
.....
T1cy4u       : 정보
T179lgs7     : 콘솔
Tygvmh7      : 에러
`

**Comment by petersirka** [comment]
Yes. I have added `?language=` to the WebSocket address. I think that now it will work, please:

- download `flow.package` https://github.com/totaljs/flow
- restart app
- give me a feedback

**Comment by KangGeunSu** [comment]
I checked what came over.

In index.js, "client.language" should be changed to "client.query.language".
client.language is undefined
client.query.language is language of Value(ko)

**Comment by KangGeunSu** [comment]
Or you can use "client.req.$language".

**Comment by KangGeunSu** [comment]
Has confirmed.
Thank you all the time.
Have a good day!
