### ISSUE TITLE
FlowV4 If you add a controller, Route doesn't work. 

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/flow#63]
I am making a login page using Auth.

If you add default.js to the controller, httproute.js does not work.

This is my file structure.
![image](https://user-images.githubusercontent.com/11586458/113544361-111bfa00-9623-11eb-8acf-05af81f989da.png)

what's the problem?

**Comment by KangGeunSu** [comment]
Please check...

**Comment by petersirka** [comment]
Hi, we have updated HttpRoute component.

Update:

- Update Total.js framework
- Flow package
- HttpRoute component

I belive that it will work.

**Comment by KangGeunSu** [comment]
All of them have been tested with the latest version.

But it doesn't work yet.

There is no 'isUNIQUE' attribute under 'F.routes.web'.

`[ { path: '/',
    hash: 0,
    id: null,
    apiname: undefined,
    name: '',
    priority: 0,
    sitemap: '',
    schema: undefined,
    novalidate: false,
    workflow: undefined,
    subdomain: null,
    description: undefined,
    controller: 'unknown',
    owner: 'package_flow',
    urlraw: '/',
    url: [ '/' ],
    param: [],
    paramidindex: -1,
    paramnames: null,
    paramtypes: null,
    flags: [ 'get' ],
    flags2: { get: true },
    method: 'GET',
    execute: [Function],
    length: 10240,
    middleware: null,
    timeout: 3000,
    isGET: true,
    isMULTIPLE: false,
    isJSON: false,
    isXML: false,
    isRAW: false,
    isENCRYPT: false,
    isMOBILE: false,
    isROBOT: false,
    isMOBILE_VARY: false,
    MEMBER: 0,
    isWILDCARD: false,
    isROLE: false,
    isREFERER: false,
    isHTTPS: false,
    isHTTP: false,
    isDEBUG: false,
    isRELEASE: false,
    isBOTH: true,
    isXHR: false,
    isUPLOAD: false,
    isSYSTEM: false,
    isPARAM: false,
    isDELAY: false,
    isDYNAMICSCHEMA: false,
    isAPI: false,
    CUSTOM: null,
    options: undefined,
    type: 'web',
    parent: { route: [Circular] },
    compare: [Function],
    isUNIQUE: true,
    currentViewDirectory: '' },
  { path: '/login',
    hash: 1448719514,
    id: null,
    apiname: undefined,
    name: '/login',
    priority: 0,
    sitemap: '',
    schema: undefined,
    novalidate: false,
    workflow: undefined,
    subdomain: null,
    description: undefined,
    controller: 'default',
    owner: 'controller_default',
    urlraw: '/login/',
    url: [ 'login' ],
    param: [],
    paramidindex: -1,
    paramnames: null,
    paramtypes: null,
    flags: [ 'get' ],
    flags2: { get: true },
    method: 'GET',
    execute: [Function: view_login],
    length: 10240,
    middleware: null,
    timeout: 3000,
    isGET: true,
    isMULTIPLE: false,
    isJSON: false,
    isXML: false,
    isRAW: false,
    isENCRYPT: false,
    isMOBILE: false,
    isROBOT: false,
    isMOBILE_VARY: false,
    MEMBER: 0,
    isWILDCARD: false,
    isROLE: false,
    isREFERER: false,
    isHTTPS: false,
    isHTTP: false,
    isDEBUG: false,
    isRELEASE: false,
    isBOTH: true,
    isXHR: false,
    isUPLOAD: false,
    isSYSTEM: false,
    isPARAM: false,
    isDELAY: false,
    isDYNAMICSCHEMA: false,
    isAPI: false,
    CUSTOM: null,
    options: undefined,
    type: 'web',
    parent: { route: [Circular] },
    compare: [Function],
    isUNIQUE: true },
  { path: 'GET /test 5000,id:1620609715122',
    hash: 46961985,
    id: '1620609715122',
    apiname: undefined,
    name: '/test',
    priority: 0,
    sitemap: '',
    schema: undefined,
    novalidate: false,
    workflow: undefined,
    subdomain: null,
    description: undefined,
    controller: 'default',
    owner: 'controller_default',
    urlraw: '/test/',
    url: [ 'test' ],
    param: [],
    paramidindex: -1,
    paramnames: null,
    paramtypes: null,
    flags: [ 'get' ],
    flags2: { get: true },
    method: 'GET',
    execute: [Function: handler],
    length: 5120,
    middleware: null,
    timeout: 5000,
    isGET: true,
    isMULTIPLE: false,
    isJSON: false,
    isXML: false,
    isRAW: false,
    isENCRYPT: false,
    isMOBILE: false,
    isROBOT: false,
    isMOBILE_VARY: false,
    MEMBER: 0,
    isWILDCARD: false,
    isROLE: false,
    isREFERER: false,
    isHTTPS: false,
    isHTTP: false,
    isDEBUG: false,
    isRELEASE: false,
    isBOTH: true,
    isXHR: false,
    isUPLOAD: false,
    isSYSTEM: false,
    isPARAM: false,
    isDELAY: false,
    isDYNAMICSCHEMA: false,
    isAPI: false,
    CUSTOM: null,
    options: undefined,
    type: 'web',
    parent: { route: [Circular] },
    compare: [Function] } ]
`

/ : flow (action)
/login : controllers/default.js (action)
/test : flow's httproute (not action)

**Comment by petersirka** [comment]
Can you send me a simple Flow project with that route and all `node_modules`? I'll test it.

**Comment by KangGeunSu** [comment]
If **controllers/default.js** is deleted, it works normally.

/test  flow's httproute (action 200 OK)

If you add default.js to the controller, httproute.js does not work.

**Comment by KangGeunSu** [comment]
An error occurs

`Cannot find module 'worker_threads'`

Thank you

**Comment by petersirka** [comment]
Hmm, Total.js 4 needs Node.js +14. But it will work with +12 and worker threads are part of Node.js v12.

**Comment by KangGeunSu** [comment]
OK I'll try.

**Comment by KangGeunSu** [comment]
Confirmed
Thank You!!
