### ISSUE TITLE
Component update Error

### ISSUE THREAD

**Issue by KangGeunSu** [totaljs/flow#64]
Hello,

I get an error when I update "Component" from "total4@0.0.44".

`TypeError: Cannot set property paused of #<Object> which has only a getter TypeError: Cannot set property paused of #<Object> which has only a getter`

If you deploy any component and reinstall it, an error occurs.

Thank you.

**Comment by petersirka** [comment]
Fixed. I have published a new beta version of the Total.js framework: `$ npm install total4@beta`.
I assume that new official release will be next week.

**Comment by KangGeunSu** [comment]
Confirmed! Thank you
