### ISSUE TITLE
Communication with Vuejs and Totaljs.

### ISSUE THREAD

**Issue by Rahul139-stack** [totaljs/flow#71]
Hi peter Sirka, 
I'm using Total.js flow inside my Vue Project. I'd like to know, how can I communicate between Vue.js & Total.Js flow.
I'm running flow inside an iframe & after getting a response from an API inside flow, I want to pass the response to the Vue (Vuex Store).
As I can't access browser storage inside flow, Is there any other to communicate?

**Comment by petersirka** [comment]
Hi @Rahul139-stack,
I don't see any problem to connect e.g. your Vue app with the Flow via API. Maybe you can create a WebSocket connection for obtaining real-time data, or you can use standard AJAX requests.

**Comment by Rahul139-stack** [comment]
Thank you @petersirka
