### ISSUE TITLE
how to register a new user?

### ISSUE THREAD

**Issue by kenbankuk** [totaljs/flow#74]
Does anyone know how to register a new user? And where can I find the registered users' data? 

After the installation, it gives the user a default account. But how can I create a new account if there are more than 1 user want to use FLOW?

**Comment by kenbankuk** [comment]
because after the installation, it gives the user a default account. But how can I create a new account if there are more than 1 user want to use FLOW?

**Comment by petersirka** [comment]
@kenbankuk The Flow supports only one user - the administrator. User data + configuration are stored locally on HDD in the `databases` directory. Flow data are stored in the `/flowstream/databases.json` file.

**Comment by kenbankuk** [comment]
@petersirka  thank you very much, Peter. May I ask one more question? Is there anyway to tranform the FLOW to a multiple user web app?

**Comment by petersirka** [comment]
@kenbankuk sorry, I forgot to answer... Is this still open for you?

**Comment by kenbankuk** [comment]
@petersirka much appreciated, Peter. It is still open 👍

**Comment by petersirka** [comment]
> @petersirka thank you very much, Peter. May I ask one more question? Is there anyway to tranform the FLOW to a multiple user web app?

How do you mean it? Do you need own Flow every web app with an individual user access?

**Comment by petersirka** [comment]
@kenbankuk Can I close this issue?

**Comment by kenbankuk** [comment]
@petersirka Hi Peter, Sorry for late replying. I was thinking about this, but I don't know whether there is any better solution. My plan is to store users' and flows' data in a "cloud" database. All the Flow web apps can access this database. And the Flow web app is stored in the docker. a new docker file is cloned and assigned to the new user when the new user is trying to access the Flow web app. But this plan sounds very stupid and need to waste lots of resources.

**Comment by petersirka** [comment]
@kenbankuk It's possible, I don't see any problem with it.

**Saving action:**
- https://github.com/totaljs/flow/blob/master/definitions/flowstream.js#L24

**Reading action:**
- https://github.com/totaljs/flow/blob/master/definitions/flowstream.js#L100

---

All you need to do is create a Docker container or something else to execute the flow.
