### ISSUE TITLE
how to replace "flowstream/database.json" with mysql database

### ISSUE THREAD

**Issue by kenbankuk** [totaljs/flow#78]
Hi, 

Really sorry for bothering again. I want to replace the local database"flowstream/database.json" with a cloud based mysql datebase. How should I do that? Anyone can kindly show me an example. 

I tried to do that myself, but it didn't work...

Thanks a lot.

**Comment by petersirka** [comment]
Hi @kenbankuk,
you need to modify these lines of code:
https://github.com/totaljs/flow/blob/master/definitions/flowstream.js#L41

There is a mechanism for writing and reading that file. Nothing more.

**Comment by kenbankuk** [comment]
@petersirka many thanks Peter.
