### ISSUE TITLE
Real-time traffic indicator delay

### ISSUE THREAD

**Issue by ColtonMcInroy** [totaljs/flow#79]
I have noticed that the "real-time traffic indicator" does not actually appear to be real-time or close to real time. I find generally it takes about 2-3+ seconds before the indicator flows. Every once in a while it will be right on time but it is rather rare. In a very basic example with a trigger going to Print JSON component, clicking the trigger will result in Print JSON being updated right away, but 2-3+ seconds later the real-time traffic indicator starts movement. The behaviour is not consistent and sometimes appear to be sent in bursts rather than based on real-time behaviour. I would expect at least the initial traffic indicator to start at close to the same time. End time obviously is based on how long the animation time is. Perhaps an area in the options to adjust the animation options (animation time, color, size, style)?

**Comment by petersirka** [comment]
Yes, Yes, it's on purpose for performance reasons. You need to keep in mind that some Flows can generate thousands of messages and the counter is synchronized every few seconds (it's optimized well and thought from the old version of Flow). It's not exactly a real-time indicator, but it mirrors usage.

Changing colors, sizes and styles of dots is not possible to do right now. However, I don't see anything wrong with customizing Flow.
