### ISSUE TITLE
Link Color Significance

### ISSUE THREAD

**Issue by ColtonMcInroy** [totaljs/flow#80]
I created a flow with various components starting with HTTP Routes and it worked fine. Then I added colour to the lines, making red lines paths to error, blue to unauthenticated, and green to authenticated requests all of a sudden the flow didn't work properly. After some troubleshooting I realised the colours was what was causing the problem. I removed all the colours the flow worked fine again.

So I decided to test a basic example making a trigger output to some Code/Forward components then to a Read JSON component and started playing with the colours but everything appears to work just fine. I couldn't see any documentation about the significance of colours and when taking a brief look at the code I saw nothing in regards to the colours, before deep diving into the code I figured best ask here. Any details or documents you can point me to about this would be appreciated.

**Comment by petersirka** [comment]
Flowing data can be sorted based on connection/line colors.

**Rules:**
- The data will Flow only for a specific color (except black)
- The color black is in this case a universal color and it will transport everything

**Simple example:**

![image](https://user-images.githubusercontent.com/2414252/212894632-805af754-77b4-4f46-8ef8-e9363df3e125.png)

As you can see, the green line/connection color will only transmit data along the green or black connections. There is a lack of documentation - @Will-create, could you add this information to the documentation?

**Comment by Will-create** [comment]
@ColtonMcInroy  The documentation of `Forward` component is updated.

**Comment by petersirka** [comment]
@ColtonMcInroy We will release all updated components this week because we changed the old declaration for UI components for a more modern one.

@Will-create thank you.

**Comment by ColtonMcInroy** [comment]
It would be nice if there was more control of flexibility with the colours. I have noticed that the message depends on the last line colour it was on. Take this for example...

![image](https://user-images.githubusercontent.com/121206906/214193134-b7a0f487-905c-47c4-b7de-c368442590a7.png)

Here because the message started with a colour but then went over a line with no colour it goes ends up going to both colours in the forward because it last went down a non-coloured line and that changed the messages associated colour. Having the ability to preserve the message colour would add an additional level of flexibility. Perhaps having the ability to click on a connection dot or input/output line and configure some options such as preserve message colour, reset colour, force a colour, ignore colour and always send, etc.

**Comment by petersirka** [comment]
@ColtonMcInroy Data don't remember color. Data are sent in the same color as they are received, except for black. Nothing more.

If you keep the same color throughout your flow, it will work.
