### ISSUE TITLE
Export Bug

### ISSUE THREAD

**Issue by ColtonMcInroy** [totaljs/flow#83]
I built a large flow with a bunch of custom components and stuff then downloaded the flow. I deployed Flow into a docker container with the following volumes...
    volumes:
      - ./databases:/www/databases
      - ./flowstream:/www/flowstream
I stopped the container and rebuilt it with the latest commits then restarted the container. The flows didn't appear to get saved, so it was a good thing I choose to download the Flow. But when I went to go import it, some of the component appear to have new lines in the wrong place resulting in the JSON schema being invalid. I manually edited the JSON to join the lines together then imported it an it worked so something is wrong with the export/download feature when components contain a lot of code.

**Comment by Will-create** [comment]
@ColtonMcInroy **some of the component appear to have new lines in the wrong place resulting in the JSON...** Can you prepare example of this?

**Comment by ColtonMcInroy** [comment]
Here is one I am playing around with.

When I chose to download it I get this file...

[GraphQL.zip](https://github.com/totaljs/flow/files/10484349/GraphQL.zip)

There are some broken new lines. If I chose to Copy JSON I get a valid JSON export, but the downloaded file has broken lines resulting in invalid JSON.

**Comment by ColtonMcInroy** [comment]
Sorry, this was my bad. I opened the file with Kate to paste into the import field and I didn't realise that Kate was actually causing the issues NOT the export. Perhaps add an import by file option?

**Comment by Will-create** [comment]
@ColtonMcInroy. Okay we will take it into consideration. Thank you

**Comment by petersirka** [comment]
@Will-create I have fixed one "critical" bug in the `j-Flow` UI component (designer). It could cause some problems when exporting. It would be great to test it on your side.

- Repository is updated
- Docker is updated
