### ISSUE TITLE
Ques : Is there a way, we can just publish only flow and not designer section, so flow become read only

### ISSUE THREAD

**Issue by aniket-work** [totaljs/flow#91]

**Comment by aniket-work** [comment]
1st of all, thanks much for such an amazing product, I am trying to learn it and was wondering if there is a way if I just build a flow and then publish as some url, which is read only (in other words , only show flow in action, but not the left hand side designer section)

**Comment by petersirka** [comment]
Thank you. Currently it's not possible to switch Flow to read-only mode, but we will think about it this week. Personally, I don't think it's a big problem to add it. The question is, from where will users be able to enable read-only mode? Is it possible to remove the read-only Flow or will it remain read-only for specific users?
