### ISSUE TITLE
Docker Persistent storage example

### ISSUE THREAD

**Issue by nate8199** [totaljs/flow#96]
I've been poking around other issues on here looking for this with no luck so far.  Do you have a docker compose example with persistent storage volumes?  I would like to try this out but I don't want to lose it whenever I update docker.

**Comment by AmsellemJoseph** [comment]
Hey, I would also be interested 😊

**Comment by petersirka** [comment]
Sorry for the delay. Look at this:
https://github.com/totaljs/code-docker-flow/blob/main/docker-compose.yaml

Just replace `##FOLDER_WWW##` with your local path and remove `environment` + `networks`.
